[workspace]
resolver = "2"
members = [
    "crates/emu-core",
    "crates/gb-core",
    "crates/gba-core",
    "platforms/desktop",
    "platforms/cli",
    "platforms/wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
emu-core = { path = "crates/emu-core" }
gb-core = { path = "crates/gb-core" }
gba-core = { path = "crates/gba-core" }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3